name: CI Build

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - # Ubuntu 22.04 x86_64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: x86_64
        - # Ubuntu 22.04 arm64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_arm64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: arm64
        - # Ubuntu 22.04 riscv64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_riscv64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: riscv64
        - # Ubuntu 24.04 x86_64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2404_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "24.04"
          cpu-architecture: x86_64
        - # Ubuntu 24.04 arm64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2404_arm64:latest
          distribution-id: ubuntu
          distribution-version: "24.04"
          cpu-architecture: arm64
        - # Ubuntu 24.04 riscv64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2404_riscv64:latest
          distribution-id: ubuntu
          distribution-version: "24.04"
          cpu-architecture: riscv64
    steps:
    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/arm64, linux/riscv64
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Run build in container
      if: runner.os == 'Linux'
      run: |
        docker run --rm \
          -v "${PWD}:/workspace" \
          -w /workspace \
          ${{ matrix.platform.image }} \
          ./build_artifact.py \
            ${{ matrix.platform.distribution-id }} \
            ${{ matrix.platform.distribution-version }} \
            ${{ matrix.platform.cpu-architecture }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts_${{ matrix.platform.distribution-id }}_${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}
        path: build/repository
